apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frisk-frontend
  tags:
    - internal
spec:
  type: website
  lifecycle: deprecated
  owner: skvis
  system: system:default/funksjon-skjema-register
