# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "frisk-frontend"
  tags:
  - "internal"
spec:
  type: "website"
  lifecycle: "production"
  owner: "skvis"
  system: "funksjon-skjema-register"