# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "frisk-frontend"
  tags:
  - "internal"
spec:
  type: "website"
  lifecycle: "production"
  owner: "skvis"
  system: "sikkerhetsmetrikker"
---
apiVersion: "backstage.io/v1alpha1"
kind: "Group"
metadata:
  name: "security_champion_frisk-frontend"
  title: "Security Champion frisk-frontend"
spec:
  type: "security_champion"
  parent: "eiendom_security_champions"
  members:
  - "larsore"
  children:
  - "resource:frisk-frontend"
---
apiVersion: "backstage.io/v1alpha1"
kind: "Resource"
metadata:
  name: "frisk-frontend"
  links:
  - url: "https://github.com/kartverket/frisk-frontend"
    title: "frisk-frontend på GitHub"
spec:
  type: "repo"
  owner: "security_champion_frisk-frontend"
  dependencyOf:
  - "component:frisk-frontend"
