name: Fly preview
on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, closed]

permissions: write-all

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_ORG_TOKEN }}

jobs:
  staging_app:
    runs-on: ubuntu-latest
    # Only run one deployment at a time per PR.
    concurrency:
      group: pr-${{ github.event.number }}

    # Create a GitHub deployment environment per staging app so it shows up
    # in the pull request UI.
    environment:
      name: frisk-pr-${{ github.event.number }}
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy
        id: deploy
        uses: superfly/fly-pr-review-apps@main
        with:
          dockerfile: ./Dockerfile
          name: frisk-pr-${{ github.event.number }}
          org: FRISK
      
      - name: Set secrets in Fly
        if: ${{ github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'synchronize' }}
        run: |
          flyctl secrets set -a frisk-pr-${{ github.event.number }} \
          VITE_CLIENT_ID=3e09bdb6-734c-473e-ab69-1238057dfc5d \
          VITE_AUTHORITY=https://login.microsoftonline.com/7531b79e-fd42-4826-bff2-131d82c7b557/v2.0 \
          VITE_LOGIN_REDIRECT_URI=https://frisk-pr-${{ github.event.number }}.fly.dev \
          VITE_BACKEND_URL=https://frisk-backend.fly.dev \
          VITE_REGELRETT_FRONTEND_URL=https://regelrett-frontend-1024826672490.europe-north1.run.app \

      - name: Update image
        if: ${{ github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'synchronize' }}
        run: flyctl image update -a frisk-pr-${{ github.event.number }} --skip-health-checks -y

      - name: Clean up GitHub environment
        uses: strumwolf/delete-deployment-environment@v2
        if: ${{ github.event.action == 'closed' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: frisk-pr-${{ github.event.number }}